# Generated by Django 5.0.3 on 2024-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(auto_now_add=True, max_length=8),
        ),
    ]
