# Generated by Django 5.0.3 on 2024-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_rename_desciption_subject_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teacher'},
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(default='2024', max_length=5),
        ),
    ]
