# Generated by Django 5.0.3 on 2024-04-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecolumn',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
