# Generated by Django 5.0.3 on 2024-04-18 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_scorecolumn_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetails',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
