# Generated by Django 5.0.3 on 2024-04-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_alter_scoredetails_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoredetails',
            unique_together={('study', 'scorecolumn')},
        ),
    ]
