# Generated by Django 5.0.3 on 2024-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_alter_scoredetails_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
