# Generated by Django 5.0.3 on 2024-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_alter_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(default='2023 - 2024', max_length=11),
        ),
    ]
