# Generated by Django 5.0.3 on 2024-05-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0011_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
