# Generated by Django 5.0.3 on 2024-05-22 05:06

import django.db.models.deletion
import score.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0012_remove_user_role_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'ADMIN'), ('student', 'STUDENT'), ('teacher', 'TEACHER')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[score.models.User.validate_ou_mail]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='score.role'),
        ),
    ]
