# Generated by Django 5.0.3 on 2024-05-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0015_alter_student_code_alter_teacher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentclassroom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='score.studentclassroom'),
        ),
    ]
