# Generated by Django 5.0.3 on 2024-05-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0016_alter_student_studentclassroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
