# Generated by Django 5.0.3 on 2024-05-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0018_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
