# Generated by Django 5.0.3 on 2024-06-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0021_alter_topic_title_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='code',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
    ]
