# Generated by Django 5.0.3 on 2024-06-11 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0022_remove_student_code_remove_teacher_code_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetails',
            name='score',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
