# Generated by Django 5.0.3 on 2024-08-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0024_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyclassroom',
            unique_together={('subject', 'semester')},
        ),
    ]
