# Generated by Django 5.0.3 on 2024-08-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0025_alter_studyclassroom_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyclassroom',
            unique_together=set(),
        ),
    ]
