# Generated by Django 5.0.3 on 2024-08-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0026_alter_studyclassroom_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyclassroom',
            name='started_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studyclassroom',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('started_time', models.DateTimeField(null=True)),
                ('ended_time', models.DateTimeField(null=True)),
                ('studyclassroom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='score.studyclassroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
