# Generated by Django 5.0.3 on 2024-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0027_studyclassroom_started_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyclassroom',
            name='ended_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studyclassroom',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
