# Generated by Django 5.0.3 on 2024-08-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0028_studyclassroom_ended_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('started_time', 'ended_time', 'studyclassroom')},
        ),
    ]
