# Generated by Django 5.0.3 on 2024-08-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0030_commentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
