# Generated by Django 5.0.3 on 2024-08-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0031_alter_commentfile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='descriptions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
