# Generated by Django 5.0.3 on 2024-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0032_schedule_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfile',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
