# Generated by Django 5.0.3 on 2024-08-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0033_commentfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
