# Generated by Django 5.0.3 on 2024-08-22 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0034_schedule_google_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='studyclassroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='score.studyclassroom'),
        ),
    ]
