# Generated by Django 5.0.3 on 2024-08-23 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0035_alter_study_studyclassroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_point_scale_max', models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('ten_point_scale_min', models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('four_point_scale', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('grade', models.CharField(max_length=2, null=True)),
            ],
            options={
                'unique_together': {('ten_point_scale_max', 'ten_point_scale_min', 'four_point_scale', 'grade')},
            },
        ),
    ]
