# Generated by Django 5.0.3 on 2024-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0036_pointconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
