# Generated by Django 5.0.3 on 2024-08-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0037_alter_commentfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyclassroom',
            name='isregister',
            field=models.BooleanField(default=True),
        ),
    ]
