# Generated by Django 5.0.3 on 2024-08-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0038_studyclassroom_isregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfile',
            name='file_asset_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentfile',
            name='file_public_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentfile',
            name='file_resource_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commentfile',
            name='file_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
