# Generated by Django 5.0.3 on 2024-09-13 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0039_commentfile_file_asset_id_commentfile_file_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='ended_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='started_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('started_date', models.DateField(null=True)),
                ('ended_date', models.DateField(null=True)),
                ('descriptions', models.CharField(max_length=100, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='score.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
