# Generated by Django 5.0.3 on 2024-09-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0040_semester_ended_date_semester_started_date_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ended_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='started_date',
        ),
        migrations.AddField(
            model_name='event',
            name='ended_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='started_time',
            field=models.DateTimeField(null=True),
        ),
    ]
