# Generated by Django 5.0.3 on 2024-09-20 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0047_rename_descriptions_event_description_event_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=5, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='score.schedule')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='score.study')),
            ],
            options={
                'unique_together': {('study', 'schedule')},
            },
        ),
    ]
