# Generated by Django 5.0.3 on 2024-10-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0048_attend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='title',
        ),
    ]
