import { StyleSheet } from "react-native";

export default StyleSheet.create({
  class: {
    width: "100%",
    backgroundColor: "#99ffff",
    padding: 10,
    marginTop: 10,
    justifyContent: "center",
    borderWidth: 2,
    borderRadius: 10,
  },
  text_class: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
  text_red_color: {
    color: "#fa0707",
  },
  topic: {
    width: "100%",
    marginBottom: 10,
    padding: 10,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderRadius: 10,
  },
  button_topic: {
    width: 200,
  },
  addTopic_Comment: {
    width: "100%",
    marginBottom: 10,
    padding: 10,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "black",
  },
  button_del: {
    backgroundColor: "#ff0000",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 5,
    flexDirection: "row",
    alignItems: "center",
  },
  buttonText_del: {
    color: "#fff",
    textAlign: "center",
    marginLeft: 5,
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
    backgroundColor: "#99ebff",
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  bellIconContainer: {
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
  },
  notificationLabel: {
    fontSize: 18,
    fontWeight: "600",
    marginRight: 8,
  },
  bellIcon: {
    marginHorizontal: 8,
  },
  badge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#FF5252",
    color: "#fff",
    fontSize: 12,
  },
  popoverContainer: {
    backgroundColor: "#f9f9f9",
    padding: 10,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  notificationItem: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  notificationText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },
  topicTitle: {
    color: "#4CAF50",
    fontWeight: "bold",
  },
  notificationTime: {
    fontSize: 14,
    color: "#777",
    marginTop: 4,
    fontStyle: "italic",
  },
  noNotificationText: {
    textAlign: "center",
    fontSize: 16,
    color: "#555",
    marginTop: 20,
  },
});
